### ISSUE TITLE
Facilitate command development by supporting dev versions

### ISSUE THREAD

**Issue by dergachev** [backtickbacktick/backtick#23]
Let's say I add this command to backtick: https://gist.github.com/dergachev/8291018

If I remember correctly, backtick will extract the following URL and store it for future retrieval and evaluation: https://gist.github.com/dergachev/8291018/raw/f1df7576b3358be8fb9805eb48df25b7e87b8b76/command.js

This is great for security and stability (your commands don't break or go malware on you), but annoying for development. Currently I need to constantly remove and re-add commands in backtick whenever I make any tweaks to the gist.

Perhaps we could implement a checkbox or some other way of indicating that you'd like to execute the following URL instead:

https://gist.github.com/dergachev/8291018/raw/command.js

**Comment by iambriansreed** [comment]
Not sure about the old command but the new version runs the command.js at the gist url. No code is downloaded and cached.
