### ISSUE TITLE
Link to http://lyoshenka.github.io/backticklist/ to facilitate command discovery.

### ISSUE THREAD

**Issue by lyoshenka** [backtickbacktick/backtick#26]
This way everyone doesn't have to reinvent the wheel every time.

**Comment by iambriansreed** [comment]
Will use this for the library page of the new site. 

Also keeping a curated library of commands in a repo:
https://github.com/backtickbacktick/library

**Comment by iambriansreed** [comment]
Rewrote the script in node generating the cached list.
Check out the new library page.
https://backtick.ninja/#library
