### ISSUE TITLE
Dynamically pass params to command

### ISSUE THREAD

**Issue by rastasheep** [backtickbacktick/backtick#32]
It would be great that you can create "meta" commands with placeholders, and pass options dynamically.

So it would add possibility for commands like: `open:tw` `open:fb` (in this case option separator is `:`) and in my command some placeholder would be replaced with params `alert('opening $PARAM')` would become `alert('opening tw')`.

**Comment by iambriansreed** [comment]
This is like issue https://github.com/backtickbacktick/backtick/issues/34.

Planning on build a proper command line integration with actual command and params.
Still in the planning phase.
