### ISSUE TITLE
Feature Request: allow export / sync 

### ISSUE THREAD

**Issue by asfaltboy** [backtickbacktick/backtick#36]
It would be useful if I were to load backtick on another machine / chrome profile and wanted to quickly get up and running. This should include the backtick shortcut, and custom commands. Ideally this could be done using some chrome sync mechanism.

**Comment by iambriansreed** [comment]
The new version just deployed should carry over commands with Chrome sync.

**Comment by iambriansreed** [comment]
Double checked this is working, both with the library commands and custom commands/gists. Neato!
